//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int IDPrestamo { get; set; }
        public string NombrePersona { get; set; }
        public int IDLibro { get; set; }
        public System.DateTime FechaPrestamoInicio { get; set; }
        public System.DateTime FechaPrestamoFin { get; set; }
    
        public virtual Libros Libros { get; set; }
    }
}
